apiVersion: v1
kind: Secret
metadata:
  name: my-database-secret
type: Opaque
data:
  DATABASE_PASSWORD: QXAwMHJQYSQkdzByZCE=

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        env:
        - name: POSTGRES_DB
          value: postgres
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-database-secret
              key: DATABASE_PASSWORD
        ports:
        - containerPort: 5432

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: final_assignment-backend
        imagePullPolicy: Never
        env:
        - name: db_address
          value: postgres-service
        - name: db_username
          value: postgres
        - name: db_name
          value: postgres
        - name: db_password
          valueFrom:
            secretKeyRef:
              name: my-database-secret
              key: DATABASE_PASSWORD
        ports:
        - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000

---

apiVersion: v1
kind: Namespace
metadata:
  name: crud-app